### ISSUE TITLE
Can't compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-demo#26]
I downloaded and tried to compile it on Ubuntu 18.04 but encountered the following error messages.
demo.c:38:10: fatal error: conio.h: No such file or directory
demo.c:40:10: fatal error: cbm.h: No such file or directory

Apparently this was written for an MSDOS compiler. I don't believe these two include files are necessary and they should either be commented out or deleted.

**Comment by Frank-Buss** [comment]
Your cc65 version might be too old. What says "cc65 --version" ? I tested it with V2.18.

**Comment by Frank-Buss** [comment]
But you are right, all these includes are not needed. Fixed here:
https://github.com/commanderx16/x16-demo/pull/29

**Comment by MCPEmaniac** [comment]
I'm also using cc65 V2.18 but on Ubuntu 18.04 Linux instead of Windows.

**Comment by Frank-Buss** [comment]
That's strange, then it should work, because the conio.h and cbm.h files are part of CC65 and shouldn't matter if it is used on Linux or Windows. I use Windows as well.
But my patch is merged now, you can checkout the demo again, and then "make" should work.

**Comment by MCPEmaniac** [comment]
I don't have the required tools for generating the balloon sprite so I commented out the balloon sprite and replaced it with my own sprite and the program seems to work on R31. I noticed the program doesn't seem to halt and return to the kernel when I hit the Esc key, but I've notice that on other programs as well.

I noticed the following statement in the program, but the BSOUT symbol doesn't seem to be defined anywhere in the program. Is BSOUT a symbol provided by CC65?
    __asm__("jsr BSOUT");

**Comment by Frank-Buss** [comment]
Yes, BSOUT is defined in the CC65 startup code which is used if you compile a program for C64.
