### ISSUE TITLE
cc65-sprite demo doesn't appear to work

### ISSUE THREAD

**Issue by 3vi1** [commanderx16/x16-demo#9]
It compiles fine on my Linux host (using cc65 V2.17 - Ubuntu 2.17-1), but when I run it in the emulator I get this result: 
 https://youtu.be/ZIYJwpen0zA

It seems to just hang on exit and the emulator goes to 100% CPU.  I'm assuming that's not what it's supposed to do.

Tested with pre-built Linux binary and with x16emu built from source.

**Comment by ElfEars** [comment]
The makefile is missing the assembler and linking steps

Replace the demo.prg: segment with the following and tell me if it works (it did for me)

cc65 -t c64 -O -o demo.s demo.c
ca65 -t c64 demo.s
ld65 -t c64 -o demo demo.o c64.lib

**Comment by 3vi1** [comment]
This was _almost_ fixed with the latest commit, and rebuilding the emu from current source.  Unfortunately that commit has an error on line 167. 

08:21:08 evil@P950ER ~/src/x16-demo/cc65-sprite» make
cl65 -t c64 -O -o demo.prg demo.c
demo.c(167): Error: Invalid input character with code 24
demo.c(167): Error: Undefined symbol: `f'
demo.c(167): Error: Too few arguments in function call
demo.c(167): Error: `)' expected
make: *** [Makefile:4: demo.prg] Error 1

If you change it from $f to 0xf it works as expected.
